language: ruby
cache: bundler
bundler_args: "--without development"
rvm:
- ruby-head
- 3.0
- 2.7
- 2.6
- 2.5
- 2.4
- jruby-9.2
services:
- docker
install: make install
script: make test
matrix:
  allow_failures:
  - rvm: ruby-head
  fast_finish: true
deploy:
- provider: script
  script: make docker-build && make docker-push
  skip_cleanup: true
  on:
    tags: true
    rvm: '2.4'
- provider: rubygems
  api_key: "$RUBYGEMS_APIKEY"
  on:
    tags: true
    rvm: '2.4'
notifications:
  slack:
    if: branch = main
    on_pull_requests: false
    on_success: never
    on_failure: change
    rooms:
      secure: OkXuxf75AYfH919/hhfY3IZOb6IzN3p74ouG2U860Vdwku1WzXjIutq0PnTeL7frqd+jbQgJmKcc3lbVXFZM0r96t8EsAuvXXx9ZWl7GuxpNUKAxwOqAY80m1b6Os7175MKeRyGnfvW8HTX14O7UmyYIJp5HrfN9dU1D1ZMUTDw=
